apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: model-api-monitor
  namespace: monitoring
  labels:
    release: prom
spec:
  selector:
    matchLabels:
      app: model
  namespaceSelector:
    matchNames:
      - default
  endpoints:
    - port: metrics
      path: /
      interval: 15s
      scrapeTimeout: 10s
