apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: streamlit
  name: streamlit
spec:
  replicas: 3
  selector:
    matchLabels:
      app: streamlit
  template:
    metadata:
      labels:
        app: streamlit
    spec:
      containers:
      - image: ghcr.io/mbakalarski/mlops-bootcamp-house-price-predictor-streamlit:f69724edcca9f05116622bbb8f579bf5af815e97
        name: streamlit
